export const searchEngines = [
    { key: 'google', name: 'Google', baseUrl: 'https://www.google.com/search', queryParam: 'q' },
    { key: 'bing', name: 'Bing', baseUrl: 'https://www.bing.com/search', queryParam: 'q' },
    { key: 'duckduckgo', name: 'DuckDuckGo', baseUrl: 'https://duckduckgo.com/', queryParam: 'q' },
    { key: 'yandex', name: 'Yandex', baseUrl: 'https://yandex.com/search/', queryParam: 'text' }
];

export const dorkCategories = [
    { id: 'basic', description: 'PHP endpoints with query parameters', query: 'site:{domain} ext:php inurl:?' },
    { id: 'wildcardOne', description: 'Wildcard subdomain search', query: 'site:"*<{domain}>*"' },
    { id: 'api', description: 'REST and versioned API endpoints', query: 'site:{domain} inurl:api | site:*/rest | site:*/v1 | site:*/v2 | site:*/v3' },
    { id: 'extensions', description: 'Logs, configs, backups, and sensitive extensions', query: 'site:"{domain}" ext:log | ext:txt | ext:conf | ext:cnf | ext:ini | ext:env | ext:sh | ext:bak | ext:backup | ext:swp | ext:old | ext:~ | ext:git | ext:svn | ext:htpasswd | ext:htaccess | ext:json' },
    { id: 'inurl', description: 'Sensitive paths such as config, admin, and backup', query: 'inurl:conf | inurl:env | inurl:cgi | inurl:bin | inurl:etc | inurl:root | inurl:sql | inurl:backup | inurl:admin | inurl:php site:{domain}' },
    { id: 'errors', description: 'Error messages, exceptions, and stack traces', query: 'inurl:"error" | intitle:"exception" | intitle:"failure" | intitle:"server at" | inurl:exception | "database error" | "SQL syntax" | "undefined index" | "unhandled exception" | "stack trace" site:{domain}' },
    { id: 'xss', description: 'Pages with common search and reflection parameters', query: 'inurl:q= | inurl:s= | inurl:search= | inurl:query= | inurl:keyword= | inurl:lang= inurl:& site:{domain}' },
    { id: 'redirect', description: 'Common redirect parameter names', query: 'inurl:url= | inurl:return= | inurl:next= | inurl:redirect= | inurl:redir= | inurl:ret= | inurl:r2= | inurl:page= inurl:& inurl:http site:{domain}' },
    { id: 'sqli', description: 'Common database-related parameter names', query: 'inurl:id= | inurl:pid= | inurl:category= | inurl:cat= | inurl:action= | inurl:sid= | inurl:dir= inurl:& site:{domain}' },
    { id: 'ssrf', description: 'URL, path, destination, and domain parameters', query: 'inurl:http | inurl:url= | inurl:path= | inurl:dest= | inurl:html= | inurl:data= | inurl:domain= | inurl:page= inurl:& site:{domain}' },
    { id: 'lfi', description: 'File, folder, include, and document parameters', query: 'inurl:include | inurl:dir | inurl:detail= | inurl:file= | inurl:folder= | inurl:inc= | inurl:locate= | inurl:doc= | inurl:conf= inurl:& site:{domain}' },
    { id: 'rce', description: 'Command and execution-related parameter names', query: 'inurl:cmd | inurl:exec= | inurl:query= | inurl:code= | inurl:do= | inurl:run= | inurl:read= | inurl:ping= inurl:& site:{domain}' },
    { id: 'upload', description: 'Pages that may offer file uploads', query: 'site:{domain} "choose file"' },
    { id: 'apidocs', description: 'Swagger, API docs, and API explorers', query: 'inurl:apidocs | inurl:api-docs | inurl:swagger | inurl:api-explorer site:"{domain}"' },
    { id: 'login', description: 'Login, registration, admin, and authentication pages', query: 'site:{domain} inurl:signup | inurl:register | intitle:Signup | inurl:admin | inurl:login | inurl:adminlogin | inurl:cplogin | inurl:weblogin | inurl:quicklogin | inurl:wp-admin | inurl:wp-login | inurl:portal | inurl:userportal | inurl:loginpanel | inurl:memberlogin | inurl:remote | inurl:dashboard | inurl:auth | inurl:exchange | inurl:ForgotPassword' },
    { id: 'test', description: 'Test, development, staging, and debug environments', query: 'inurl:test | inurl:env | inurl:dev | inurl:staging | inurl:sandbox | inurl:debug | inurl:temp | inurl:internal | inurl:demo site:{domain}' },
    { id: 'docs', description: 'Documents containing confidentiality terms', query: 'site:{domain} ext:txt | ext:pdf | ext:xml | ext:xls | ext:xlsx | ext:ppt | ext:pptx | ext:doc | ext:docx intext:"confidential" | intext:"Not for Public Release" | intext:"internal use only" | intext:"do not distribute"' },
    { id: 'params', description: 'Sensitive parameter names', query: 'inurl:email= | inurl:phone= | inurl:password= | inurl:secret= inurl:& site:{domain}' },
    { id: 'aem', description: 'Adobe Experience Manager paths', query: 'inurl:/content/usergenerated | inurl:/content/dam | inurl:/jcr:content | inurl:/libs/granite | inurl:/etc/clientlibs | inurl:/content/geometrixx | inurl:/bin/wcm | inurl:/crx/de site:{domain}' },
    { id: 'disclosed', description: 'OpenBugBounty reports mentioning the domain', query: 'site:openbugbounty.org inurl:reports intext:"{domain}"' },
    { id: 'groups', description: 'Google Groups mentions', query: 'site:groups.google.com "{domain}"' },
    { id: 'gitFolders', description: 'Indexed .git folder references', query: 'inurl:"/.git" {domain} -github' },
    { id: 'backupFiles', description: 'Backup files such as bkf, bkp, bak, and old', query: 'site:{domain} ext:bkf | ext:bkp | ext:bak | ext:old | ext:backup' },
    { id: 'exposedDocs', description: 'Common document and data file formats', query: 'site:{domain} ext:doc | ext:docx | ext:odt | ext:pdf | ext:rtf | ext:sxw | ext:psw | ext:ppt | ext:pptx | ext:pps | ext:csv | filetype:doc | filetype:docx | filetype:xls | filetype:xlsx | filetype:ppt | filetype:pptx | filetype:mdb | filetype:pdf | filetype:sql | filetype:txt | filetype:rtf | filetype:csv | filetype:xml | filetype:conf | filetype:dat | filetype:ini | filetype:log' },
    { id: 'confidential', description: 'Documents with private or proprietary labels', query: 'inurl:{domain} not for distribution | confidential | "employee only" | proprietary | top secret | classified | trade secret | internal | private filetype:xls OR filetype:csv OR filetype:doc OR filetype:pdf' },
    { id: 'configFiles', description: 'Configuration files such as XML, ENV, and INI', query: 'site:{domain} ext:xml | ext:conf | ext:cnf | ext:reg | ext:inf | ext:rdp | ext:cfg | ext:txt | ext:ora | ext:env | ext:ini' },
    { id: 'databaseFiles', description: 'SQL and database files', query: 'site:{domain} ext:sql | ext:dbf | ext:mdb' },
    { id: 'otherFiles', description: 'Directory listings, diagnostic pages, and known sensitive paths', query: 'site:{domain} intitle:index.of | ext:log | ext:php intitle:phpinfo "published by the PHP Group" | inurl:shell | inurl:backdoor | inurl:wso | inurl:cmd | shadow | passwd | boot.ini | inurl:readme | inurl:license | inurl:install | inurl:setup | inurl:config | inurl:"/phpinfo.php" | inurl:".htaccess" | ext:swf' },
    { id: 'sqlErrors', description: 'SQL syntax errors and database warnings', query: 'site:{domain} intext:"sql syntax near" | intext:"syntax error has occurred" | intext:"incorrect syntax near" | intext:"unexpected end of SQL command" | intext:"Warning: mysql_connect()" | intext:"Warning: mysql_query()" | intext:"Warning: pg_connect()"' },
    { id: 'phpErrors', description: 'PHP parse errors and warnings', query: 'site:{domain} "PHP Parse error" | "PHP Warning" | "PHP Error"' },
    { id: 'wordpress', description: 'WordPress content and include paths', query: 'site:{domain} inurl:wp-content | inurl:wp-includes' },
    { id: 'projectMgmt', description: 'Trello and Atlassian project references', query: ['site:trello.com "{domain}"', 'site:*.atlassian.net "{domain}"'] },
    { id: 'subdomains', description: 'Indexed subdomains', query: 'site:*.{domain}' },
    { id: 'subSubdomains', description: 'Indexed second-level subdomains', query: 'site:*.*.{domain}' },
    { id: 'directoryListing', description: 'Directory listings and common exposed folders', query: '"{domain}" intitle:"index of" "parent directory" | intitle:"index of" "DCIM" | intitle:"index of" "ftp" | intitle:"index of" "backup" | intitle:"index of" "mail" | intitle:"index of" "password" | intitle:"index of" "pub" | intitle:"index of" ".git"' },
    { id: 'gitRepos', description: 'GitHub, GitLab, and Bitbucket references', query: ['site:github.com "{domain}"', 'site:gitlab.com "{domain}"', 'site:bitbucket.org "{domain}"'] },
    { id: 'traefik', description: 'Traefik dashboard references', query: 'intitle:traefik inurl:8080/dashboard "{domain}"' },
    { id: 'jenkins', description: 'Jenkins dashboard references', query: 'intitle:"Dashboard [Jenkins]" "{domain}"' },
    { id: 'openRedirects', description: 'Common redirect URL parameters', query: 'site:{domain} inurl:redir | inurl:url | inurl:redirect | inurl:return | inurl:src=http | inurl:r=http' },
    { id: 'codeShare', description: 'Code-sharing site references', query: ['site:sharecode.io "{domain}"', 'site:controlc.com "{domain}"', 'site:codepad.co "{domain}"', 'site:ideone.com "{domain}"', 'site:jsdelivr.com "{domain}"', 'site:codeshare.io "{domain}"', 'site:repl.it "{domain}"'] },
    { id: 'thirdParty', description: 'Third-party sites and package references', query: ['site:gitter.im "{domain}"', 'site:papaly.com "{domain}"', 'site:productforums.google.com "{domain}"', 'site:coggle.it "{domain}"', 'site:ycombinator.com "{domain}"', 'site:libraries.io "{domain}"', 'site:npm.runkit.com "{domain}"', 'site:npmjs.com "{domain}"', 'site:scribd.com "{domain}"'] },
    { id: 'stackoverflow', description: 'Stack Overflow mentions', query: 'site:stackoverflow.com "{domain}"' },
    { id: 'pastebinSites', description: 'Paste sites mentioning the domain', query: ['site:justpaste.it "{domain}"', 'site:heypasteit.com "{domain}"', 'site:pastebin.com "{domain}"'] },
    { id: 'apacheStruts', description: 'Apache Struts-related file extensions', query: 'site:{domain} ext:action | ext:struts | ext:do' },
    { id: 'linkedinEmployees', description: 'LinkedIn employee references', query: 'site:linkedin.com employees {domain}' },
    { id: 'leaks', description: 'Code paste sites mentioning the domain', query: ['site:pastebin.com "{domain}"', 'site:jsfiddle.net "{domain}"', 'site:codebeautify.org "{domain}"', 'site:codepen.io "{domain}"'] },
    { id: 'cloud', description: 'Cloud storage and hosted document references', query: ['site:s3.amazonaws.com "{domain}"', 'site:blob.core.windows.net "{domain}"', 'site:googleapis.com "{domain}"', 'site:storage.googleapis.com "{domain}"', 'site:drive.google.com "{domain}"', 'site:dev.azure.com "{domain}"', 'site:onedrive.live.com "{domain}"', 'site:digitaloceanspaces.com "{domain}"', 'site:sharepoint.com "{domain}"', 'site:s3-external-1.amazonaws.com "{domain}"', 'site:s3.dualstack.us-east-1.amazonaws.com "{domain}"', 'site:dropbox.com/s "{domain}"', 'site:box.com/s "{domain}"', 'site:docs.google.com inurl:"/d/" "{domain}"', 'site:amazonaws.com "{domain}"'] },
    { id: 'jfrog', description: 'JFrog Artifactory references', query: 'site:jfrog.io "{domain}"' },
    { id: 'firebase', description: 'Firebase-hosted database references', query: 'site:firebaseio.com "{domain}"' },
    { id: 'securitytxt', description: 'security.txt files mentioning bounty programs', query: 'site:*/security.txt "bounty"' }
];